apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app
  namespace: my-app
  labels:
    app: my-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      imagePullSecrets:
        - name: nexus-registry-secret

      containers:
        - name: my-app
          image: 192.168.38.136:8083/devsecops-app:38-eb1cfe1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          securityContext:
            runAsUser: 1001
            runAsGroup: 101
            runAsNonRoot: true
            allowPrivilegeEscalation: false
